apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: notifications
  name: notifications
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notifications
  template:
    metadata:
      labels:
        app: notifications
    spec:
      containers:
      - env:
        - name: TCP_PORT
          value: '3000'
        - name: GOOGLE_OAUTH_CLIENT_ID
          value: 861387520592-smsr63m8tkcp8ocem12ojiqeh1jpcb73.apps.googleusercontent.com
        - name: SMTP_USER
          value: sleeperapplication@gmail.com
        - name: GOOGLE_OAUTH_CLIENT_SECRET
          value: 'clientSecret'
        - name: GOOGLE_OAUTH_REFRESH_TOKEN
          value: 'refreshToken'
        image: gitregistry.bas.kz/bas-bpm/bas-bpm-backend/bas-bpm-notifications:latest
        name: notifications
        ports:
          - containerPort: 3000
      imagePullSecrets:
      - name: bas-gitregistry-robot