services:
  auth:
    image: gitregistry.bas.kz/bas-bpm/bas-bpm-backend/bas-bpm-auth:latest
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: pnpm run start:dev auth
    env_file:
      - ./apps/auth/.env
    ports:
      - '3001:3000'
    volumes:
      - .:/usr/src/app
  notifications:
    image: gitregistry.bas.kz/bas-bpm/bas-bpm-backend/bas-bpm-notifications:latest
    build:
      context: .
      dockerfile: ./apps/notifications/Dockerfile
      target: development
    command: pnpm run start:dev notifications
    env_file:
      - ./apps/notifications/.env
    volumes:
      - .:/usr/src/app
