import {
  PrimaryGeneratedColumn,
  CreateDateColumn,
  UpdateDateColumn,
  BaseEntity,
} from 'typeorm';

export abstract class AbstractEntity extends BaseEntity {
  @PrimaryGeneratedColumn('uuid')  // Generates a UUID for the primary key
  id: string;

  @CreateDateColumn({ name: 'created_at' })  // Automatically managed by TypeORM
  createdAt: Date;

  @UpdateDateColumn({ name: 'updated_at' })  // Automatically updated by TypeORM
  updatedAt: Date;
}

export type AutoGeneratedField = 'id' | 'createdAt' | 'updatedAt';
